# Generated by Django 5.2.5 on 2025-12-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_video', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
    ]
